project:
  type: book
  preview:
    port: 7777

book:
  title: "R for the Rest of Us: A Statistics-Free Introduction"
  repo-url: https://github.com/rfortherestofus/book
  repo-actions: [source, issue]
  open-graph: 
    site-name: "R for the Rest of Us: A Statistics-Free Introduction"
    image: assets/featured-image.png
  favicon: assets/r-treasure-chest.png
  site-url: https://book.rfortherestofus.com/
  body-header: | 
    ###### You are reading the free online version of this book. If you'd like to purchase a physical or electronic copy, you can buy it from [No Starch Press](https://nostarch.com/r-rest-us), [Powell's](https://www.powells.com/book/r-for-the-rest-of-us-9781718503328), [Barnes and Noble](https://www.barnesandnoble.com/w/r-for-the-rest-of-us-david-keyes/1145069854?ean=9781718503328) or [Amazon](https://a.co/d/fzAMxMV). 
  
  sidebar:
    logo: assets/cover.jpg



  chapters:
    - index.qmd
    - introduction.qmd

    - part: "Part I: Visualizations"
      chapters:
        - crash-course.qmd
        - data-viz.qmd
        - themes.qmd
        - maps.qmd
        - tables.qmd

    - part: "Part II: Reports, Presentations, and Websites"
      chapters:
        - rmarkdown.qmd
        - parameterized-reporting.qmd
        - presentations.qmd
        - websites.qmd
        - quarto.qmd

    - part: "Part III: Automation and Collaboration"
      chapters:
        - accessing-data.qmd
        - packages.qmd

    - errata.qmd
    - text: "Purchase"
      href: purchase.qmd

engine: knitr

execute: 
  eval: true
  echo: false
  warning: false
  message: false
  output: true
  include: true
  cache: true

format:
  html:
    include-after-body: figure-caption.html
    page-layout: full
    callout-icon: false
    smooth-scroll: true
    theme: 
      - cosmo
      - style.scss
    code-link: true
    number-depth: 0
    grid:
      sidebar-width: 350px
    filters:
       - quarto
      

    author-meta: "David Keyes"
    include-in-header: "scipts.html"
    callout-appearance: simple

