project:
  type: book
  preview:
    port: 7777

book:
  title: "R for the Rest of Us: A Statistics-Free Introduction"
  repo-url: https://github.com/rfortherestofus/book
  repo-actions: issue
  open-graph: 
    site-name: "R for the Rest of Us: A Statistics-Free Introduction"
    image: assets/featured-image.png

  page-footer:
    left: |
      R for the Rest of Us: A Statistics-Free Introduction
    right: |
      This book can be purchased from No Starch Press.
  
  sidebar:
    logo: assets/cover.jpg
    # style: "docked"
    # background: "white"
    # border: false
    # alignment: "center"

  # cover-image: assets/cover.jpg
  favicon: assets/r-treasure-chest.png
  site-url: https://book.rfortherestofus.com/

  chapters:
    - index.qmd
    - introduction.qmd

    - part: "Part I: Visualizations"
      chapters:
        - crash-course.qmd
        - data-viz.qmd
        - themes.qmd
        - maps.qmd
        - tables.qmd

    - part: "Part II: Reports, Presentations, and Websites"
      chapters:
        - rmarkdown.qmd
        - parameterized-reporting.qmd
        - presentations.qmd
        - websites.qmd
        - quarto.qmd

    - part: "Part III: Automation and Collaboration"
      chapters:
        - accessing-data.qmd
        - packages.qmd

engine: knitr

execute: 
  eval: true
  echo: false
  warning: false
  message: false
  output: true
  include: true
  cache: true
  out-width: "100%"

format:
  html:
    page-layout: full
    callout-icon: false
    smooth-scroll: true
    theme: 
      - cosmo
      - style.scss
    code-link: true
    number-depth: 0
    grid:
      sidebar-width: 350px
    filters:
      - change-figure-formatting.lua
      - quarto
      

    author-meta: "David Keyes"
    include-in-header: "fathom.html"
    callout-appearance: simple

